<a href="https://colab.research.google.com/github/Sophie-GJ/deep-learning-challenge/blob/main/Sophie_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
df = df.drop(['EIN', 'NAME'], axis = 1)
df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [3]:
# Determine the number of unique values in each column.
df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
app_types = df['APPLICATION_TYPE'].value_counts()
app_types

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff = 450
apps = df['APPLICATION_TYPE'].value_counts()
application_types_to_replace = apps[apps > cutoff].index

# Replace in dataframe
for app in application_types_to_replace:
    df['APPLICATION_TYPE'] = df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
df['APPLICATION_TYPE'].value_counts()

Other    34023
T9         156
T13         66
T12         27
T2          16
T25          3
T14          3
T29          2
T15          2
T17          1
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
df['CLASSIFICATION' ].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
lower_limit = 1
app_class = df['CLASSIFICATION'].value_counts()
big_classes = app_class[app_class > lower_limit]
big_classes

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
class_cutoff = 1000
classes = df['APPLICATION_TYPE'].value_counts()
classifications_to_replace = app_class[app_class > class_cutoff].index

# Replace in dataframe
for cls in classifications_to_replace:
   df['CLASSIFICATION'] = df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
df['CLASSIFICATION'].value_counts()

Other    32038
C7000      777
C1700      287
C4000      194
C5000      116
         ...
C4120        1
C8210        1
C1245        1
C2561        1
C2150        1
Name: CLASSIFICATION, Length: 67, dtype: int64

In [9]:
df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,Other,Independent,Other,ProductDev,Association,1,0,N,5000,1
1,Other,Independent,Other,Preservation,Co-operative,1,1-9999,N,108590,1
2,Other,CompanySponsored,Other,ProductDev,Association,1,0,N,5000,0
3,Other,CompanySponsored,Other,Preservation,Trust,1,10000-24999,N,6692,1
4,Other,Independent,Other,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,Other,Independent,Other,ProductDev,Association,1,0,N,5000,0
34295,Other,CompanySponsored,Other,ProductDev,Association,1,0,N,5000,0
34296,Other,CompanySponsored,Other,Preservation,Association,1,0,N,5000,0
34297,Other,Independent,Other,ProductDev,Association,1,0,N,5000,1
34298,Other,Independent,Other,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [10]:
# Convert categorical data to numeric with `pd.get_dummies`
dummy_df = pd.get_dummies(df[['APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION', 'USE_CASE', 'ORGANIZATION', 'INCOME_AMT', 'SPECIAL_CONSIDERATIONS']])
combined_df = pd.concat([df, dummy_df], axis=1)
combined_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,Other,Independent,Other,ProductDev,Association,1,0,N,5000,1,...,0,0,0,0,0,0,0,0,1,0
1,Other,Independent,Other,Preservation,Co-operative,1,1-9999,N,108590,1,...,1,0,0,0,0,0,0,0,1,0
2,Other,CompanySponsored,Other,ProductDev,Association,1,0,N,5000,0,...,0,0,0,0,0,0,0,0,1,0
3,Other,CompanySponsored,Other,Preservation,Trust,1,10000-24999,N,6692,1,...,0,1,0,0,0,0,0,0,1,0
4,Other,Independent,Other,Heathcare,Trust,1,100000-499999,N,142590,1,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,Other,Independent,Other,ProductDev,Association,1,0,N,5000,0,...,0,0,0,0,0,0,0,0,1,0
34295,Other,CompanySponsored,Other,ProductDev,Association,1,0,N,5000,0,...,0,0,0,0,0,0,0,0,1,0
34296,Other,CompanySponsored,Other,Preservation,Association,1,0,N,5000,0,...,0,0,0,0,0,0,0,0,1,0
34297,Other,Independent,Other,ProductDev,Association,1,0,N,5000,1,...,0,0,0,0,0,0,0,0,1,0
34298,Other,Independent,Other,Preservation,Co-operative,1,1M-5M,N,36500179,0,...,0,0,0,0,1,0,0,0,1,0

In [11]:
combined_df = combined_df.drop(['APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION', 'USE_CASE', 'ORGANIZATION', 'INCOME_AMT', 'SPECIAL_CONSIDERATIONS'], axis=1)
combined_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T2,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [12]:
# Split our preprocessed data into our features and target arrays
y = combined_df['IS_SUCCESSFUL'].values
X = combined_df.drop(['IS_SUCCESSFUL'], 1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=7)

<ipython-input-12-7e1202bc001f>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  X = combined_df.drop(['IS_SUCCESSFUL'], 1).values

In [13]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [46]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features = len(X_train[0])
hidden_nodes1 = 4
hidden_nodes2 = 15
hidden_nodes3 = 5

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes1, input_dim=input_features, activation="relu")
)

# Second hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes2, input_dim=input_features, activation="relu")
)

# Third hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes3, input_dim=input_features, activation="relu")
)

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_33 (Dense)            (None, 4)                 424

 dense_34 (Dense)            (None, 15)                75

 dense_35 (Dense)            (None, 5)                 80

 dense_36 (Dense)            (None, 1)                 6

=================================================================
Total params: 585 (2.29 KB)
Trainable params: 585 (2.29 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [47]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [48]:
# Train the model
model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 3ms/step - loss: 0.6230 - accuracy: 0.6740
Epoch 2/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5959 - accuracy: 0.6967
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5935 - accuracy: 0.6976
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5928 - accuracy: 0.6997
Epoch 5/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5921 - accuracy: 0.6988
Epoch 6/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5918 - accuracy: 0.6997
Epoch 7/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5914 - accuracy: 0.6997
Epoch 8/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5914 - accuracy: 0.6998
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5912 - accuracy: 0.6999
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5909 - accuracy: 0.7000
Epoch 11/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5908 - accuracy: 0.7004
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5906 - accuracy: 0.6989
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5905 - accuracy: 0.7004
Epoch 14/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5906 - accuracy: 0.7006
Epoch 15/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5905 - accuracy: 0.7009
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5904 - accuracy: 0.7006
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5900 - accuracy: 0.7005
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5902 - accuracy: 0.6997
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5900 - accuracy: 0.7006
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5902 - accuracy: 0.7010
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5900 - accuracy: 0.7008
Epoch 22/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5895 - accuracy: 0.7013
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5894 - accuracy: 0.6997
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5894 - accuracy: 0.7008
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5896 - accuracy: 0.7010
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5895 - accuracy: 0.6998
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5895 - accuracy: 0.7009
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5891 - accuracy: 0.7014
Epoch 29/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5891 - accuracy: 0.7013
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5892 - accuracy: 0.7020
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5892 - accuracy: 0.7014
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5889 - accuracy: 0.7021
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5893 - accuracy: 0.7021
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5891 - accuracy: 0.7006
Epoch 35/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5889 - accuracy: 0.7030
Epoch 36/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5888 - accuracy: 0.7015
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5889 - accuracy: 0.7016
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5888 - accuracy: 0.7018
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5887 - accuracy: 0.7015
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5888 - accuracy: 0.7021
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5888 - accuracy: 0.7011
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5888 - accuracy: 0.7014
Epoch 43/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5884 - accuracy: 0.7016
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5886 - accuracy: 0.7020
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5887 - accuracy: 0.7015
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5886 - accuracy: 0.7027
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5887 - accuracy: 0.7016
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5886 - accuracy: 0.7017
Epoch 49/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5882 - accuracy: 0.7029
Epoch 50/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5887 - accuracy: 0.7024
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5884 - accuracy: 0.7015
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5884 - accuracy: 0.7020
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5884 - accuracy: 0.7023
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5883 - accuracy: 0.7018
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5883 - accuracy: 0.7014
Epoch 56/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5884 - accuracy: 0.7024
Epoch 57/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5881 - accuracy: 0.7025
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5884 - accuracy: 0.7030
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5882 - accuracy: 0.7027
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5884 - accuracy: 0.7020
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5884 - accuracy: 0.7020
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5884 - accuracy: 0.7025
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5883 - accuracy: 0.7021
Epoch 64/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5882 - accuracy: 0.7021
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5883 - accuracy: 0.7015
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5883 - accuracy: 0.7029
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5884 - accuracy: 0.7016
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5883 - accuracy: 0.7030
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5881 - accuracy: 0.7028
Epoch 70/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5879 - accuracy: 0.7037
Epoch 71/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5883 - accuracy: 0.7033
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5879 - accuracy: 0.7022
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5883 - accuracy: 0.7026
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5880 - accuracy: 0.7030
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5880 - accuracy: 0.7022
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5880 - accuracy: 0.7029
Epoch 77/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5881 - accuracy: 0.7030
Epoch 78/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5879 - accuracy: 0.7032
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5879 - accuracy: 0.7025
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5879 - accuracy: 0.7025
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5878 - accuracy: 0.7020
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5876 - accuracy: 0.7032
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5879 - accuracy: 0.7023
Epoch 84/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5876 - accuracy: 0.7034
Epoch 85/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5880 - accuracy: 0.7032
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5876 - accuracy: 0.7027
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5876 - accuracy: 0.7020
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5878 - accuracy: 0.7019
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5877 - accuracy: 0.7024
Epoch 90/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5875 - accuracy: 0.7021
Epoch 91/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5879 - accuracy: 0.7021
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5874 - accuracy: 0.7027
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5877 - accuracy: 0.7028
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5875 - accuracy: 0.7022
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5877 - accuracy: 0.7019
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5877 - accuracy: 0.7030
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5875 - accuracy: 0.7027
Epoch 98/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5874 - accuracy: 0.7025
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5876 - accuracy: 0.7024
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5875 - accuracy: 0.7028

In [49]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5943 - accuracy: 0.6964 - 582ms/epoch - 2ms/step
Loss: 0.5942882895469666, Accuracy: 0.6964431405067444

In [50]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(